import type { Product } from '../types/product.js'

// ============================================================================
// КАТАЛОГ ТОВАРІВ
// ============================================================================
// Для додавання нового товару:
// 1. Скопіюйте шаблон з PRODUCT_TEMPLATE.md
// 2. Вставте в потрібну секцію (БОМБОЧКИ / НАБОРИ / ЧАШКИ)
// 3. Заповніть всі поля
// 4. Перевірте: npm run build
//
// Шаблон та інструкція: /shared/catalog/PRODUCT_TEMPLATE.md
// ============================================================================

// Product images can live in frontend/public/products and be referenced as:
// /products/<product-slug>/1.jpg
export const productsCatalog: Product[] = [
  // ==================== БОМБОЧКИ (6 products) ====================
  {
    id: 'caramel-cloud',
    slug: 'caramel-cloud',
    name: 'Карамельна хмаринка',
    shortDescription: 'Молочний шоколад, карамель і ніжний маршмелоу.',
    description:
      'Шоколадна бомбочка з вершковою карамеллю, міні-маршмелоу та нотами ванілі. Ідеальна для вечірнього какао або святкового подарунка.',
    composition: ['молочний шоколад', 'карамель', 'маршмелоу', 'ваніль'],
    weight: 90,
    flavor: 'Карамель',
    price: 95,
    badge: 'hit',
    category: 'classic',
    tags: ['карамель', 'подарунок', 'популярне', 'бомбочки'],
    popularity: 98,
    images: [
      { id: '1', src: '/products/color-2.png', alt: 'Карамельна бомбочка' },
      { id: '2', src: '/products/bomb_choco.png', alt: 'Бомбочка у чашці' },      
    ],
    reviewSummary: { rating: 4.9, reviewCount: 47 },
    featured: true,
  },
  {
    id: 'berry-kiss',
    slug: 'berry-kiss',
    name: 'Ягідний поцілунок',
    shortDescription: 'Темний шоколад з полуничним центром.',
    description:
      'Контрастна бомбочка на базі темного шоколаду з ягідним маршмелоу та легкою кислинкою полуниці.',
    composition: ['темний шоколад', 'сублімована полуниця', 'маршмелоу'],
    weight: 88,
    flavor: 'Полуниця',
    price: 95,
    badge: 'new',
    category: 'premium',
    tags: ['полуниця', 'темний шоколад', 'бомбочки'],
    popularity: 87,
    images: [
      { id: '1', src: '/products/color-1.png', alt: 'Ягідна бомбочка' },
      { id: '2', src: '/products/bomb_choco.png', alt: 'Бомбочка у чашці' },  
    ],
    reviewSummary: { rating: 4.8, reviewCount: 28 },
  },
  {
    id: 'hazelnut-dream',
    slug: 'hazelnut-dream',
    name: 'Горіхова мрія',
    shortDescription: 'Праліне, лісовий горіх і маршмелоу.',
    description:
      'Насичений смак фундука та шоколадного праліне для тих, хто любить виразні десертні комбінації.',
    composition: ['молочний шоколад', 'фундук', 'паста праліне', 'маршмелоу'],
    weight: 95,
    flavor: 'Фундук',
    price: 95,
    previousPrice: 104,
    badge: 'sale',
    category: 'premium',
    tags: ['горіхи', 'праліне', 'бомбочки'],
    popularity: 82,
    images: [
      { id: '1', src: '/products/color-3.png', alt: 'Горіхова бомбочка' },
      { id: '2', src: '/products/bomb_choco.png', alt: 'Бомбочка у чашці' },  
    ],
    reviewSummary: { rating: 4.7, reviewCount: 19 },
  },
  {
    id: 'vanilla-sky',
    slug: 'vanilla-sky',
    name: 'Ванільне небо',
    shortDescription: 'Білий шоколад з мадагаскарською ваніллю.',
    description:
      'Ніжна бомбочка з білого шоколаду, збагачена натуральною ваніллю та повітряним маршмелоу.',
    composition: ['білий шоколад', 'ваніль', 'маршмелоу', 'вершки'],
    weight: 85,
    flavor: 'Ваніль',
    price: 95,
    category: 'classic',
    tags: ['ваніль', 'білий шоколад', 'бомбочки'],
    popularity: 91,
    images: [
      { id: '1', src: '/products/color-4.png', alt: 'Ванільна бомбочка' },
       { id: '2', src: '/products/bomb_choco.png', alt: 'Бомбочка у чашці' }, 
    ],
    reviewSummary: { rating: 4.8, reviewCount: 35 },
  },
  {
    id: 'coconut-paradise',
    slug: 'coconut-paradise',
    name: 'Кокосовий рай',
    shortDescription: 'Тропічний кокос у молочному шоколаді.',
    description:
      'Екзотична бомбочка з кокосовою стружкою, вершковим шоколадом і ніжним маршмелоу.',
    composition: ['молочний шоколад', 'кокосова стружка', 'маршмелоу', 'кокосове молоко'],
    weight: 92,
    flavor: 'Кокос',
    price: 110,
    category: 'premium',
    tags: ['кокос', 'тропіки', 'бомбочки'],
    popularity: 85,
    images: [
      { id: '1', src: '/products/heart_white.png', alt: 'Кокосова бомбочка' },
      { id: '2', src: '/products/three_heart.png', alt: 'Кокос і шоколад' },
    ],
    reviewSummary: { rating: 4.7, reviewCount: 22 },
  },
  {
    id: 'mint-choco',
    slug: 'mint-choco',
    name: 'Мятний спалах',
    shortDescription: 'Освіжаюча мята з темним шоколадом.',
    description:
      'Бомбочка з темного шоколаду з освіжаючим мятним маршмелоу для справжніх поціновувачів.',
    composition: ['темний шоколад', 'мятний екстракт', 'маршмелоу', 'какао'],
    weight: 88,
    flavor: 'Мята',
    price: 110,
    badge: 'new',
    category: 'premium',
    tags: ['мята', 'темний шоколад', 'бомбочки'],
    popularity: 79,
    images: [
      { id: '1', src: '/products/heart_red.png', alt: 'Мятна бомбочка' },
       { id: '2', src: '/products/three_heart.png', alt: 'Кокос і шоколад' },
    ],
    reviewSummary: { rating: 4.6, reviewCount: 18 },
  },
    {
        id: 'winter-box',
        slug: 'winter-box',
        name: 'Подарунковий набір Dark Heart Box',
        shortDescription: '4 смаки в преміальному боксі.',
        description:
          'Подарунковий сет з чотирьох авторських бомбочок: карамель, ягода, фундук і класичний какао-маршмелоу.',
        composition: ['асорті шоколаду', 'маршмелоу', 'декор', 'подарункове пакування'],
        weight: 360,
        flavor: 'Асорті',
        price: 110,
        badge: 'hit',
        category: 'premium',
        tags: ['асорті', 'подарунок', 'бомбочки'],
        popularity: 99,
        images: [
          { id: '1', src: '/products/heart_chocolate.png', alt: 'Подарунковий набір' },
          { id: '2', src: '/products/three_heart.png', alt: 'Кокос і шоколад' },
        ],
        reviewSummary: { rating: 5, reviewCount: 54 },
        featured: true,
      },

  // ==================== НАБОРИ (6 products) ====================
  
  {
    id: 'classic-collection',
    slug: 'classic-collection',
    name: 'Класична колекція',
    shortDescription: '6 класичних смаків для знайомства.',
    description:
      'Ідеальний набір для першого знайомства: карамель, ваніль, полуниця, шоколад, горіх і кокос.',
    composition: ['асорті шоколаду', 'маршмелоу', 'натуральні смаки'],
    weight: 540,
    flavor: 'Асорті',
    price: 480,
    badge: 'hit',
    category: 'gift-set',
    tags: ['набір', 'класика', 'асорті', 'набори'],
    popularity: 96,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1549488497-6578b47cc8b4?auto=format&fit=crop&w=900&q=80', alt: 'Класична колекція' },
      { id: '2', src: 'https://images.unsplash.com/photo-1512918580421-b2feee3b85a6?auto=format&fit=crop&w=900&q=80', alt: 'Набір бомбочок' },
    ],
    reviewSummary: { rating: 4.9, reviewCount: 67 },
    featured: true,
  },
  {
    id: 'premium-trio',
    slug: 'premium-trio',
    name: 'Преміум тріо',
    shortDescription: '3 ексклюзивні смаки в оксамитовому футлярі.',
    description:
      'Вишуканий набір з трьох преміум бомбочок: трюфель, мятний шоколад і ягідний микс.',
    composition: ['преміум шоколад', 'ексклюзивні смаки', 'оксамитовий футляр'],
    weight: 280,
    flavor: 'Асорті',
    price: 295,
    badge: 'new',
    category: 'gift-set',
    tags: ['набір', 'преміум', 'ексклюзив', 'набори'],
    popularity: 88,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1579631542720-3a87824fff86?auto=format&fit=crop&w=900&q=80', alt: 'Преміум тріо' },
      { id: '2', src: 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?auto=format&fit=crop&w=900&q=80', alt: 'Подарункова коробка' },
    ],
    reviewSummary: { rating: 4.8, reviewCount: 31 },
  },
  {
    id: 'family-pack',
    slug: 'family-pack',
    name: 'Сімейний пакунок',
    shortDescription: '10 бомбочок для великої компанії.',
    description:
      'Великий набір з 10 бомбочок різних смаків. Вистачить на всю родину або вечірку.',
    composition: ['асорті шоколаду', 'маршмелоу', 'різні смаки'],
    weight: 900,
    flavor: 'Асорті',
    price: 790,
    previousPrice: 890,
    badge: 'sale',
    category: 'gift-set',
    tags: ['набір', 'сімейний', 'великий', 'набори'],
    popularity: 92,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1549488497-6578b47cc8b4?auto=format&fit=crop&w=900&q=80', alt: 'Сімейний пакунок' },
      { id: '2', src: 'https://images.unsplash.com/photo-1512918580421-b2feee3b85a6?auto=format&fit=crop&w=900&q=80', alt: 'Великий набір' },
    ],
    reviewSummary: { rating: 4.9, reviewCount: 43 },
  },
  {
    id: 'romantic-set',
    slug: 'romantic-set',
    name: 'Романтичний сет',
    shortDescription: 'Для особливих вечорів удвох.',
    description:
      'Ніжний набір з 4 бомбочок: полуниця, ваніль, троянда і білий шоколад. Ідеально для побачення.',
    composition: ['шоколад асорті', 'романтичні смаки', 'святкове пакування'],
    weight: 340,
    flavor: 'Асорті',
    price: 350,
    category: 'gift-set',
    tags: ['набір', 'романтика', 'подарунок', 'набори'],
    popularity: 84,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1518013431117-e698d99888f4?auto=format&fit=crop&w=900&q=80', alt: 'Романтичний сет' },
      { id: '2', src: 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?auto=format&fit=crop&w=900&q=80', alt: 'Подарунок для двох' },
    ],
    reviewSummary: { rating: 4.7, reviewCount: 26 },
  },
  {
    id: 'kids-joy',
    slug: 'kids-joy',
    name: 'Дитяча радість',
    shortDescription: '5 солодких смаків для дітей.',
    description:
      'Яскравий набір з 5 дитячих смаків: полуниця, карамель, ваніль, банан і шоколад.',
    composition: ['молочний шоколад', 'дитячі смаки', 'кольорове маршмелоу'],
    weight: 450,
    flavor: 'Асорті',
    price: 395,
    category: 'gift-set',
    tags: ['набір', 'діти', 'солодке', 'набори'],
    popularity: 90,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1549488497-6578b47cc8b4?auto=format&fit=crop&w=900&q=80', alt: 'Дитяча радість' },
      { id: '2', src: 'https://images.unsplash.com/photo-1512918580421-b2feee3b85a6?auto=format&fit=crop&w=900&q=80', alt: 'Дитячий набір' },
    ],
    reviewSummary: { rating: 4.8, reviewCount: 38 },
  },

  // ==================== ЧАШКИ (6 products) ====================
  {
    id: 'classic-mug',
    slug: 'classic-mug',
    name: 'Класична чашка ChocoPix',
    shortDescription: 'Керамічна чашка з фірмовим лого.',
    description:
      'Зручна керамічна чашка місткістю 350 мл з фірмовим логотипом ChocoPix. Ідеальна для ранкової кави або гарячого какао.',
    composition: ['кераміка', 'глазур', 'фірмовий друк'],
    weight: 320,
    flavor: 'Універсальна',
    price: 280,
    badge: 'hit',
    category: 'cups',
    tags: ['чашка', 'кераміка', 'класика', 'чашки'],
    popularity: 94,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80', alt: 'Класична чашка' },
      { id: '2', src: 'https://images.unsplash.com/photo-1577937927633-291d1e0959b6?auto=format&fit=crop&w=900&q=80', alt: 'Чашка з какао' },
    ],
    reviewSummary: { rating: 4.8, reviewCount: 52 },
    featured: true,
  },
  {
    id: 'thermo-mug',
    slug: 'thermo-mug',
    name: 'Термочашка Travel',
    shortDescription: 'Зберігає тепло до 6 годин.',
    description:
      'Стильна термочашка з подвійними стінками. Зберігає напій гарячим до 6 годин, холодним — до 3 годин.',
    composition: ['нержавіюча сталь', 'вакуумна ізоляція', 'бамбукова кришка'],
    weight: 380,
    flavor: 'Універсальна',
    price: 520,
    badge: 'new',
    category: 'cups',
    tags: ['термочашка', 'подорож', 'сталь', 'чашки'],
    popularity: 89,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1570554868546-5c403783457c?auto=format&fit=crop&w=900&q=80', alt: 'Термочашка' },
      { id: '2', src: 'https://images.unsplash.com/photo-1517668851879-8b1a26746c93?auto=format&fit=crop&w=900&q=80', alt: 'Travel чашка' },
    ],
    reviewSummary: { rating: 4.7, reviewCount: 34 },
  },
  {
    id: 'glass-mug',
    slug: 'glass-mug',
    name: 'Скляна чашка з подвійним дном',
    shortDescription: 'Прозора елегантність для ваших напоїв.',
    description:
      'Ефектна скляна чашка з подвійним дном. Створює ефект паріння напою та довго зберігає тепло.',
    composition: ['боросилікатне скло', 'подвійне дно'],
    weight: 280,
    flavor: 'Універсальна',
    price: 340,
    category: 'cups',
    tags: ['скло', 'елегантність', 'подвійне дно', 'чашки'],
    popularity: 86,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1577937927633-291d1e0959b6?auto=format&fit=crop&w=900&q=80', alt: 'Скляна чашка' },
      { id: '2', src: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80', alt: 'Чашка з подвійним дном' },
    ],
    reviewSummary: { rating: 4.6, reviewCount: 28 },
  },
  {
    id: 'ceramic-set-2',
    slug: 'ceramic-set-2',
    name: 'Набір чашок Duo',
    shortDescription: '2 ідентичні чашки для пари.',
    description:
      'Набір з двох однакових керамічних чашок по 300 мл. Чудовий подарунок для закоханих або друзів.',
    composition: ['кераміка', 'глазур', 'подарункова коробка'],
    weight: 640,
    flavor: 'Універсальна',
    price: 520,
    previousPrice: 560,
    badge: 'sale',
    category: 'cups',
    tags: ['набір', 'чашки', 'пара', 'чашки'],
    popularity: 91,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80', alt: 'Набір чашок Duo' },
      { id: '2', src: 'https://images.unsplash.com/photo-1577937927633-291d1e0959b6?auto=format&fit=crop&w=900&q=80', alt: 'Дві чашки' },
    ],
    reviewSummary: { rating: 4.8, reviewCount: 41 },
  },
  {
    id: 'latte-mug',
    slug: 'latte-mug',
    name: 'Чашка для лате Grande',
    shortDescription: 'Містка чашка для кавових шедеврів.',
    description:
      'Велика чашка місткістю 450 мл з широким вінцем. Ідеальна для лате, капучино та кавових коктейлів.',
    composition: ['кераміка', 'професійна глазур'],
    weight: 380,
    flavor: 'Універсальна',
    price: 320,
    category: 'cups',
    tags: ['лате', 'велика', 'кава', 'чашки'],
    popularity: 87,
    images: [
      { id: '1', src: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80', alt: 'Чашка для лате' },
      { id: '2', src: 'https://images.unsplash.com/photo-1570554868546-5c403783457c?auto=format&fit=crop&w=900&q=80', alt: 'Grande чашка' },
    ],
    reviewSummary: { rating: 4.7, reviewCount: 33 },
  },  
]
